# Cubo semantico
cubo_semantico = {
  'int': {
    'int': {
      '+' : 'int',
      '-' : 'int',
      '/' : 'float',
      '*' : 'int',
      '%' : 'int',
      '>' : 'bool',
      '>=' : 'bool',
      '<=' : 'bool',
      '<' : 'bool',
      '==' : 'bool',
      '!=' : 'bool',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'float': {
      '+' : 'float',
      '-' : 'float',
      '/' : 'float',
      '*' : 'float',
      '%' : 'float',
      '>' : 'bool',
      '>=' : 'bool',
      '<=' : 'bool',
      '<' : 'bool',
      '==' : 'bool',
      '!=' : 'bool',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'bool': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'string': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'list': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    }
  },
  'float': {
    'int': {
      '+' : 'float',
      '-' : 'float',
      '/' : 'float',
      '*' : 'float',
      '%' : 'float',
      '>' : 'bool',
      '>=' : 'bool',
      '<=' : 'bool',
      '<' : 'bool',
      '==' : 'bool',
      '!=' : 'bool',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'float': {
      '+' : 'float',
      '-' : 'float',
      '/' : 'float',
      '*' : 'float',
      '%' : 'float',
      '>' : 'bool',
      '>=' : 'bool',
      '<=' : 'bool',
      '<' : 'bool',
      '==' : 'bool',
      '!=' : 'bool',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'bool': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'string': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'list': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    }
  },
  'bool': {
    'int': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'float': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'bool': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'bool',
      '||' : 'bool'
    },
    'string': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'list': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    }
  },
  'string': {
    'int': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'float': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'bool': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'string': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'list': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    }
  },
  'list': {
    'int': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'float': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'bool': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'string': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    },
    'list': {
      '+' : 'ERR',
      '-' : 'ERR',
      '/' : 'ERR',
      '*' : 'ERR',
      '%' : 'ERR',
      '>' : 'ERR',
      '>=' : 'ERR',
      '<=' : 'ERR',
      '<' : 'ERR',
      '==' : 'ERR',
      '!=' : 'ERR',
      '&&' : 'ERR',
      '||' : 'ERR'
    }
  }
}

print(cubo_semantico['int']['int']['+'])
print(cubo_semantico['int']['int']['/'])
print(cubo_semantico['int']['int']['>'])
print(cubo_semantico['int']['int']['=='])
print(cubo_semantico['int']['int']['&&'])

print(cubo_semantico['int']['float']['+'])