# Cubo semantico
class Semantic_Cube:
  def __init__(self):
    self.cubo_semantico = {
      'int': {
        'int': {
          '+' : 'int',
          '-' : 'int',
          '/' : 'float',
          '*' : 'int',
          '%' : 'int',
          '>' : 'boolean',
          '>=' : 'boolean',
          '<=' : 'boolean',
          '<' : 'boolean',
          '==' : 'boolean',
          '!=' : 'boolean',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'float': {
          '+' : 'float',
          '-' : 'float',
          '/' : 'float',
          '*' : 'float',
          '%' : 'float',
          '>' : 'boolean',
          '>=' : 'boolean',
          '<=' : 'boolean',
          '<' : 'boolean',
          '==' : 'boolean',
          '!=' : 'boolean',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'boolean': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'string': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'list': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        }
      },
      'float': {
        'int': {
          '+' : 'float',
          '-' : 'float',
          '/' : 'float',
          '*' : 'float',
          '%' : 'float',
          '>' : 'boolean',
          '>=' : 'boolean',
          '<=' : 'boolean',
          '<' : 'boolean',
          '==' : 'boolean',
          '!=' : 'boolean',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'float': {
          '+' : 'float',
          '-' : 'float',
          '/' : 'float',
          '*' : 'float',
          '%' : 'float',
          '>' : 'boolean',
          '>=' : 'boolean',
          '<=' : 'boolean',
          '<' : 'boolean',
          '==' : 'boolean',
          '!=' : 'boolean',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'boolean': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'string': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'list': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        }
      },
      'boolean': {
        'int': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'float': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'boolean': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'boolean',
          '||' : 'boolean'
        },
        'string': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'list': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        }
      },
      'string': {
        'int': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'float': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'boolean': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'string': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'list': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        }
      },
      'list': {
        'int': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'float': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'boolean': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'string': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        },
        'list': {
          '+' : 'ERR',
          '-' : 'ERR',
          '/' : 'ERR',
          '*' : 'ERR',
          '%' : 'ERR',
          '>' : 'ERR',
          '>=' : 'ERR',
          '<=' : 'ERR',
          '<' : 'ERR',
          '==' : 'ERR',
          '!=' : 'ERR',
          '&&' : 'ERR',
          '||' : 'ERR'
        }
      }
    }

  def __getitem__(t1, t2, op):
    return self.cubo_semantico[t1][t2][op]